-- Create parties table
create table if not exists public.parties (
    id bigint generated by default as identity primary key,
    title text not null,
    location text not null,
    description text,
    date date not null,
    votes integer default 0,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    user_id uuid references auth.users
);

-- Set up Row Level Security (RLS)
alter table public.parties enable row level security;

-- Create policies
create policy "Anyone can view parties"
    on public.parties for select
    using (true);

create policy "Authenticated users can create parties"
    on public.parties for insert
    with check (auth.role() = 'authenticated');

create policy "Users can update their own parties"
    on public.parties for update
    using (auth.uid() = user_id);

create policy "Users can delete their own parties"
    on public.parties for delete
    using (auth.uid() = user_id);

-- Create index on user_id for better performance
create index if not exists parties_user_id_idx on public.parties(user_id);

-- Create index on date for better sorting performance
create index if not exists parties_date_idx on public.parties(date); 