-- Add latitude and longitude to parties table
alter table public.parties
add column if not exists latitude double precision,
add column if not exists longitude double precision;

-- Create comments table
create table if not exists public.comments (
    id bigint generated by default as identity primary key,
    party_id bigint references public.parties on delete cascade not null,
    user_id uuid references public.user_profiles on delete cascade not null,
    content text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
alter table public.comments enable row level security;

-- Create policies
create policy "Anyone can view comments"
    on public.comments for select
    using (true);

create policy "Authenticated users can create comments"
    on public.comments for insert
    with check (auth.role() = 'authenticated');

create policy "Users can update their own comments"
    on public.comments for update
    using (auth.uid() = user_id);

create policy "Users can delete their own comments"
    on public.comments for delete
    using (auth.uid() = user_id);

-- Create indexes for better performance
create index if not exists comments_party_id_idx on public.comments(party_id);
create index if not exists comments_user_id_idx on public.comments(user_id);
create index if not exists comments_created_at_idx on public.comments(created_at);

-- Create a view to get comments with user information
create or replace view public.comments_with_users as
select 
    c.*,
    up.email as user_email,
    up.full_name as user_name,
    up.avatar_url as user_avatar
from public.comments c
left join public.user_profiles up on c.user_id = up.id; 